env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  semi:
    - error
    - never
